In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("ggplot")

pd.set_option("display.max_columns", None)

In [3]:
tsla = pd.read_csv("../data/raw/TSLA.csv")
spy = pd.read_csv("../data/raw/SPY.csv")
bnd = pd.read_csv("../data/raw/BND.csv")

In [4]:
print("TSLA:", tsla.shape)
print("SPY :", spy.shape)
print("BND :", bnd.shape)

TSLA: (2890, 6)
SPY : (2890, 6)
BND : (2890, 6)

In [5]:
tsla.head()

,Price,Close,High,Low,Open,Volume
0,Ticker,TSLA,TSLA,TSLA,TSLA,TSLA
1,Date,NaN,NaN,NaN,NaN,NaN
2,2015-01-02,14.620667457580566,14.883333206176758,14.21733283996582,14.857999801635742,71466000
3,2015-01-05,14.005999565124512,14.433333396911621,13.810667037963867,14.303333282470703,80527500
4,2015-01-06,14.085332870483398,14.279999732971191,13.61400032043457,14.003999710083008,93928500

In [6]:
spy.head()

,Price,Close,High,Low,Open,Volume
0,Ticker,SPY,SPY,SPY,SPY,SPY
1,Date,NaN,NaN,NaN,NaN,NaN
2,2015-01-02,169.68783569335938,170.88556456408185,168.65531949719002,170.47255808561408,121465900
3,2015-01-05,166.6233367919922,168.8122661140158,166.3177160273211,168.6470660413276,169632600
4,2015-01-06,165.0539093017578,167.44934175106874,164.2609313452381,166.92894957322903,209151400

In [7]:
bnd.head()

,Price,Close,High,Low,Open,Volume
0,Ticker,BND,BND,BND,BND,BND
1,Date,NaN,NaN,NaN,NaN,NaN
2,2015-01-02,59.40542221069336,59.43417322378284,59.24010525635261,59.24729438054874,2218800
3,2015-01-05,59.57789993286133,59.59946181347681,59.441334044039344,59.470085046090965,5820100
4,2015-01-06,59.750396728515625,59.9300863673423,59.67852196972348,59.67852196972348,3887600

In [8]:
tsla.info()

<class 'pandas.DataFrame'>
RangeIndex: 2890 entries, 0 to 2889
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Price   2890 non-null   str
 1   Close   2889 non-null   str
 2   High    2889 non-null   str
 3   Low     2889 non-null   str
 4   Open    2889 non-null   str
 5   Volume  2889 non-null   str
dtypes: str(6)
memory usage: 135.6 KB

In [9]:
spy.info()

<class 'pandas.DataFrame'>
RangeIndex: 2890 entries, 0 to 2889
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Price   2890 non-null   str
 1   Close   2889 non-null   str
 2   High    2889 non-null   str
 3   Low     2889 non-null   str
 4   Open    2889 non-null   str
 5   Volume  2889 non-null   str
dtypes: str(6)
memory usage: 135.6 KB

In [10]:
bnd.info()

<class 'pandas.DataFrame'>
RangeIndex: 2890 entries, 0 to 2889
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Price   2890 non-null   str
 1   Close   2889 non-null   str
 2   High    2889 non-null   str
 3   Low     2889 non-null   str
 4   Open    2889 non-null   str
 5   Volume  2889 non-null   str
dtypes: str(6)
memory usage: 135.6 KB

In [11]:
tsla.describe()

,Price,Close,High,Low,Open,Volume
count,2890,2889,2889,2889,2889,2889
unique,2890,2826,2764,2781,2756,2877
top,Ticker,14.005999565124512,13.41866683959961,12.333333015441895,24.0,85084500
freq,1,3,3,4,4,2

In [12]:
tsla.isnull().sum()

Price     0
Close     1
High      1
Low       1
Open      1
Volume    1
dtype: int64

In [13]:
spy.isnull().sum()

Price     0
Close     1
High      1
Low       1
Open      1
Volume    1
dtype: int64

In [14]:
bnd.isnull().sum()

Price     0
Close     1
High      1
Low       1
Open      1
Volume    1
dtype: int64

In [16]:
print(tsla.columns)
print(spy.columns)
print(bnd.columns)

Index(['Price', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='str')
Index(['Price', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='str')
Index(['Price', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='str')

In [17]:
print(tsla.head())

        Price               Close                High                 Low  \
0      Ticker                TSLA                TSLA                TSLA
1        Date                 NaN                 NaN                 NaN
2  2015-01-02  14.620667457580566  14.883333206176758   14.21733283996582
3  2015-01-05  14.005999565124512  14.433333396911621  13.810667037963867
4  2015-01-06  14.085332870483398  14.279999732971191   13.61400032043457

                 Open    Volume
0                TSLA      TSLA
1                 NaN       NaN
2  14.857999801635742  71466000
3  14.303333282470703  80527500
4  14.003999710083008  93928500

In [18]:
def clean(df):
    df = df.iloc[2:].copy()
    df.rename(columns={"Price": "Date"}, inplace=True)
    df["Date"] = pd.to_datetime(df["Date"])
    df.set_index("Date", inplace=True)
    return df

tsla = clean(tsla)
spy = clean(spy)
bnd = clean(bnd)

In [ ]:
tsla.head()